# Generated by Django 5.1.7 on 2025-03-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tasks', '0002_rename_assignee_task_assignees_remove_task_duedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(related_name='assigned_tasks', to='accounts.profile'),
        ),
    ]
